spring.config.import=optional:file:.env[.properties]
spring.application.name=Auth
server.port=${SERVER_PORT:8001}
spring.profiles.active=${APP_PROFILE:local}

google.client-id=${GOOGLE_CLIENT_ID:}
google.client-secret=${GOOGLE_CLIENT_SECRET:}
google.redirect-uri=${GOOGLE_REDIRECT_URI:postmessage}

payment.service.base-url=${PAYMENT_SERVICE_BASE_URL:}
payment.internal-api-key=${PAYMENT_INTERNAL_API_KEY:}

jwt.access-token-expiration=${JWT_ACCESS_EXPIRATION:21600}
app.bootstrap.admin-initial-secret=${ADMIN_INITIAL_SECRET:}
app.security.bcrypt-strength=${BCRYPT_STRENGTH:8}
spring.jpa.properties.hibernate.default_batch_fetch_size=100

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=never
management.endpoint.prometheus.access=unrestricted
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.slo.http.server.requests=100ms,200ms,300ms,500ms,1s,2s,5s
