spring.datasource.url=${DB_URL_LOCAL:jdbc:postgresql://postgres:5432/auth_db_local}
spring.datasource.username=${DB_USER_LOCAL:postgres}
spring.datasource.password=${DB_PASSWORD_LOCAL:postgres}
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

spring.flyway.enabled=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT — local development key (DO NOT use in production)
jwt.secret=bXlTYXdpdExvY2FsRGV2ZWxvcG1lbnRTZWNyZXRLZXlUaGF0SXNMb25nRW5vdWdoRm9ySFMyNTZBbGdvcml0aG0=
