spring.config.import=optional:file:.env[.properties]
spring.application.name=Auth
server.port=${SERVER_PORT:8001}
spring.profiles.active=${APP_PROFILE:local}

jwt.access-token-expiration=${JWT_ACCESS_EXPIRATION:900}
jwt.refresh-token-expiration=${JWT_REFRESH_EXPIRATION:604800}
