#!/usr/bin/env python3
"""Generate SQL seed data for load testing.

Creates:
- 5000 users
- 2000 active buruh_mandor_assignments

Output defaults to scripts/seed_loadtest.sql.
"""

from __future__ import annotations

import argparse
import random
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

PASSWORD_HASH = "$2a$12$7r3Vh6L8yW4mPqK8Rk5s2e9Vf2Y8mW7W6lJbI8x9n2A3b4C5d6E7F"  # placeholder bcrypt hash


def esc(value: str) -> str:
    return value.replace("'", "''")


def sql_nullable(value: str | None) -> str:
    if value is None:
        return "NULL"
    return f"'{esc(value)}'"


def user_row_sql(user: dict[str, str | None]) -> str:
    return (
        "("
        f"'{user['id']}', "
        f"'{esc(user['username'] or '')}', "
        f"'{esc(user['email'] or '')}', "
        f"'{esc(user['name'] or '')}', "
        f"{sql_nullable(user['password_hash'])}, "
        f"'{esc(user['role'] or '')}', "
        f"{sql_nullable(user['mandor_certification_number'])}, "
        "NULL, "
        "NULL, "
        "TRUE, "
        "NOW(), "
        "NOW()"
        ")"
    )


def assignment_row_sql(assignment: dict[str, str]) -> str:
    return (
        "("
        f"'{assignment['id']}', "
        f"'{assignment['buruh_id']}', "
        f"'{assignment['mandor_id']}', "
        "TRUE, "
        "NOW(), "
        "NULL, "
        "NOW(), "
        "NOW()"
        ")"
    )


def generate_users(total_users: int, total_mandor: int, batch_tag: str) -> tuple[list[dict[str, str | None]], list[str], list[str]]:
    users: list[dict[str, str | None]] = []
    mandor_ids: list[str] = []
    buruh_ids: list[str] = []

    for i in range(1, total_mandor + 1):
        uid = str(uuid4())
        mandor_ids.append(uid)
        users.append(
            {
                "id": uid,
                "username": f"seed-mandor-{batch_tag}-{i}",
                "email": f"seed.mandor.{batch_tag}.{i}@example.test",
                "name": f"Seed Mandor {i}",
                "password_hash": PASSWORD_HASH,
                "role": "MANDOR",
                "mandor_certification_number": f"CERT-{batch_tag}-{i}",
            }
        )

    buruh_count = total_users - total_mandor
    for i in range(1, buruh_count + 1):
        uid = str(uuid4())
        buruh_ids.append(uid)
        users.append(
            {
                "id": uid,
                "username": f"seed-buruh-{batch_tag}-{i}",
                "email": f"seed.buruh.{batch_tag}.{i}@example.test",
                "name": f"Seed Buruh {i}",
                "password_hash": PASSWORD_HASH,
                "role": "BURUH",
                "mandor_certification_number": None,
            }
        )

    return users, mandor_ids, buruh_ids


def generate_assignments(total_assignments: int, mandor_ids: list[str], buruh_ids: list[str], rng: random.Random) -> list[dict[str, str]]:
    if total_assignments > len(buruh_ids):
        raise ValueError("total_assignments tidak boleh melebihi jumlah buruh aktif.")
    if not mandor_ids:
        raise ValueError("Minimal harus ada 1 mandor.")

    chosen_buruh = buruh_ids[:]
    rng.shuffle(chosen_buruh)
    chosen_buruh = chosen_buruh[:total_assignments]

    assignments: list[dict[str, str]] = []
    for i, buruh_id in enumerate(chosen_buruh):
        mandor_id = mandor_ids[i % len(mandor_ids)]
        assignments.append(
            {
                "id": str(uuid4()),
                "buruh_id": buruh_id,
                "mandor_id": mandor_id,
            }
        )

    return assignments


def build_sql(users: list[dict[str, str | None]], assignments: list[dict[str, str]], *, total_users: int, total_assignments: int, batch_tag: str) -> str:
    user_values = ",\n".join(user_row_sql(u) for u in users)
    assignment_values = ",\n".join(assignment_row_sql(a) for a in assignments)

    return f"""-- Auto-generated by scripts/generate_seed_sql.py
-- batch: {batch_tag}
-- users: {total_users}
-- active assignments: {total_assignments}

BEGIN;

INSERT INTO users (
    id,
    username,
    email,
    name,
    password_hash,
    role,
    mandor_certification_number,
    oauth_provider,
    oauth_provider_id,
    is_active,
    created_at,
    updated_at
)
VALUES
{user_values};

INSERT INTO buruh_mandor_assignments (
    id,
    buruh_id,
    mandor_id,
    is_active,
    assigned_at,
    unassigned_at,
    created_at,
    updated_at
)
VALUES
{assignment_values};

COMMIT;
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SQL seed for users + assignments")
    parser.add_argument("--users", type=int, default=5000, help="Total users (default: 5000)")
    parser.add_argument("--assignments", type=int, default=2000, help="Total active assignments (default: 2000)")
    parser.add_argument("--mandor", type=int, default=800, help="Total mandor users (default: 800)")
    parser.add_argument("--output", type=Path, default=Path("scripts/seed_loadtest.sql"), help="Output SQL file")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for deterministic assignment mapping")
    args = parser.parse_args()

    if args.users <= 0:
        raise ValueError("--users harus > 0")
    if args.mandor <= 0 or args.mandor >= args.users:
        raise ValueError("--mandor harus > 0 dan < --users")
    if args.assignments < 0:
        raise ValueError("--assignments tidak boleh negatif")

    batch_tag = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    rng = random.Random(args.seed)

    users, mandor_ids, buruh_ids = generate_users(args.users, args.mandor, batch_tag)
    assignments = generate_assignments(args.assignments, mandor_ids, buruh_ids, rng)

    sql = build_sql(
        users,
        assignments,
        total_users=args.users,
        total_assignments=args.assignments,
        batch_tag=batch_tag,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql, encoding="utf-8")

    print(f"Generated {args.output} with {len(users)} users and {len(assignments)} assignments")


if __name__ == "__main__":
    main()
